---
language: python
python:
  - '3.6'
before_install:
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine
install:
  - pip install -r ./requirements.txt
script:
  - molecule --debug create
    && molecule --debug converge
    && molecule --debug verify
after_script:
  - molecule destroy
env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
    - secure: 1NOpppgPDXxvQ2qii1gEzMo3IlMzoNxlAnyW1JWxRkoThFPY/4VawnVFEgPdADiG3gpAIDkj3S1kFKxDCp407hE61jNfb51ZrnAxVHEjEDIyk9/a8kJcJsXGI4/DBIF+0xDtfKtNK/GrSsNFgXy3sm5igOJf3spZcbnGMojEmMBNTgBe3R5xIXi1ynyWj7LL7Gg1CjbIBxSkFQVLpzKrRzsoEZ1fBHxQ9h9j1GVIjzoErvs6dzV6i2dXrdwreCsQ0j8vn0NdY48zJAkADOdvf06chq3RlK7pWpw9lJ9RxmwWbJ/gXrUdX8CdnzqulzbAhugCkR6w/9qSj0k/JZ+SExZj6118LYcAWvXVnqPIadAhV60cAGyL7IEyYnSdU7wNX/ZwCijrhsLlvfxPTPgCrXfydt/39pRiQ1Jfvw4WBeVqrykSCCoggqBxNih95fi//C4IwX8QeqgsVPo0AA/aLmRHYwA1jF/QRMVjiX8cjPGZXJaY25wkQx/Us3x1DQ732nioqWvMqCppt74G0lWWRazhNjgzZ0oJxWB6H9JaeicYtxABXpB4dzFT0avPVOkRuAcSNFFnZWii7cPhPu3fWFBg8bD5ZlVfx3hwFwMqfnG0KH072Qqvkf0lVkG4uj/VJuJkZP3mN8PftKLuU1zAKz+GLcrpou30M4uSaMy6AO4=
    - secure: qll5aFA6nezarZDv0CK1qfNQwNduUu+WkKjl6waQ7KMtZca6NNCWAEYfVimchm/bfjan2FUgVR0vBVcydfgVfEU5/ZBfBbBOeSEmShxtGop59RLLeWnQOBoawgLWAekqpZ0XqFQxXV4nA6MJ5WLku6hOTA9zz+MV0nVs6uHxW4L+8WvE2gy8jCTLRtTNjelnTN37CjFpOJPkHGrn8Hp1y6f2uZczxUz1S8FxY66bpSSRtwOoMw73bFlvqT7MBEYfk9h6UufQIzwYsHociMZqkLq2jDotJTvcXRUNpeEMJjSOcse7aD5HSAQC7Sk5GNE9MnwrifWLyEU5zRsQ9FYyOIYaJxg1jlP13kyGLSG7rXuWFxFWKi131nx2CHKHkD/eq7L6czdZkaeakK5S0g7gjTzRt5P6q038Jnovedwxij6XMMrmRgDwb9IP/ASHqfRL0kXNVox3CSRNquIQ6duN1GpjXabv+XGDFVWuA2dWBrpEBhOcPCfMwNGgIIXjV3kwevUNkFMvV9dLEEH1IgNi6x9CEyjHi8kcx3Sbfk6al+u9Ld2S6gl3nmTBpXm+ExZMu0g70FaWjf+eOyG/ZtboSt0t0Te0NTezWH9ntcYCQcmGxBekgJKDW7rCqt7XPIqAaKxAwyRTLkxxYLRqDoOBRqyS5/SDb8M1RHbrsL09Hn4=
    - secure: Wn5SWzF44gAJIYkksuefISaE2qvYQuJ6uSCMDlIetoV9bVetOOlht1i4H4E0XN0QHVxyiRVcGxMvniIAI4fzkcLbIy7xz3NgDQKR478bwwL7yEd0hR/0mjMWzlJt9ypBPrhoueDyn5tr4nmCX/NM4VcH+KYcBxBE9I4AEaBrw+1rHsCT8bZ15C9YN3VMqphR86nFndU9GcrvScMbr560iw4cuIKZS0J057I3M7mXWNNZGwXqU00ia/VDQsf753EkxTx3RMcSvsrxtNS4w0zN5FKrA6iREodlOJwJXeAlRhC31k+X9Ozskz1/RDZr7aTGM7nBJXhCpZQ2KuBnhuNARmzI/cDaysVWJk9RV0FGDvyFH4S2rBh+Sivgvghhoqk8LXx/AIpR9hVmTgZQ+qOYMT9lQA7LVer6beIp4pduzn9xi1RlLMF9nTOWFdynuipM3rpus6Zy34SlvkgzQ72hlfJF/vcQyJ8pdmFs31WIVgOyx458pWN5if0ycpNqb7l+oMT0NdbAr2MqKfL2HtD/cGTX2u7WkZ/g5fE0nJulinx2uCdvwk5yawlcONK+jP1JfvsNbO00vnRqNz7Ttd8RqbOH0hAP2I3a1a78mCU8Alrw6D2yEJEZLZlIDmHN7X7ScSgOHKRL/KlSRrTMEHZ6b9RNqp7de4fwHi02+yLcQ1E=
notifications:
  slack:
    rooms:
      secure: TCtZpEvFQkJ++Liypz+qXgqKJwU3D5Zf+i316QhLL4OjohjDaQgOY4SP8536inuINp/3CMPmwmxA3Re6bqpOrMSXbnBljCuIV3YpBsPOX4w2jG8urHMw3FQ+G10DIKIolFa2C/ie22quSePzGBHTKcXNFkVl1ogaEYfA8pskOTe8DMM4oYO8xYs3BWsw9ADGG0b8TGk/bkrD6Tgjoz9bJEb/N5H0iTeIOZgUowA3U7SVAMcXkwGONDhKFBvC5zBSMtRKauuvyYoGd7rhKdyCRLjN09JOKz9Cu9ZO4TIk4fYoYUZ/Ps61iuuo35BPEY6OsCe9Lp6puuwn3CCdEkH6wVVn4qPr80LQM5DvDCUeyeb2ZH+Xzs6CSTDQkjVTYdB6aF3+qKefNGdzuEYjXH6JBmsoDE2vJFvF6W2drr5ZWo5ToBiJXHO6IYu+Q9R/esxo8CtYKAq1MxgvSd7PdZS2eY5NGwTqHI33PmFXOBjoVufrYZcqgJW6vGOTjQZIHNt8PRoFnkp5fN9lsud7Ybb5RMNWJ7IoLtColr5vW1hMtznC1tFpDn+aE9vaco63HKtc6FAP9n3eZzxddhRAJS5xxMETnOgP4l27yxpKp436ajuaVBHtbAncJ7HMke4CNLJJS8rD971piMN+TjQ/60kJMEsW5fFmU31L55Sv+s2Y/2o=
