- name: Add APT key
  # Предложенный в задании вариант падает с ошибкой "E: There were unauthenticated packages"
  apt_key: url=https://www.mongodb.org/static/pgp/server-3.2.asc
  tags: install

- name: Add APT repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install

- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
    state: started
  tags: install
